services:
  # 前端服务
  frontend:
    container_name: aireview-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - aireview_network
    restart: unless-stopped

  # 后端服务
  backend:
    container_name: aireview-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=AIreview
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - db
    networks:
      - aireview_network
    restart: unless-stopped

  # 数据库服务
  db:
    container_name: aireview-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=AIreview
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
      - ./数据库文件/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aireview_network
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

networks:
  aireview_network:
    driver: bridge

volumes:
  db_data: 